### ISSUE TITLE
Unable to run the benchmark locally

### ISSUE THREAD

**Issue by wouterj** [L3tum/php-router-benchmark#1]
I get quite some errors, most of them I don't know how to fix, when trying to run this locally.

1. First, when I run `make prepare`, I get this:
    ```
   ...
   cd routers/riaf/src && rm -rf Generated
   /bin/sh: 1: cd: can't cd to routers/riaf/src
   make: *** [Makefile:58: clean] Error 2
   ```
   If I then create `routers/riaf/src/Generated`, `make prepare` works.
2. But then, running `make benchmark-table` I get errors for FastRoute and Riaf:
   ```
    PhpBench\Remote\Exception\ScriptErrorException PHP Fatal error:  Uncaught Error: Class "Riaf\Router" not found in /home/wouter/projects/github.com/L3tum/php-router-benchmark/benchmark/RiafBench.php:15
    Stack trace:
    #0 /tmp/PhpBenchbqUszG(41): Benchmark\RiafBench->getRouter()
    #1 {main}
      thrown in /home/wouter/projects/github.com/L3tum/php-router-benchmark/benchmark/RiafBench.php on line 15
   ```
   ```
    PhpBench\Remote\Exception\ScriptErrorException PHP Warning:  Undefined array key "handler" in /home/wouter/projects/github.com/L3tum/php-router-benchmark/benchmark/FastRouteBench.php on line 41
    PHP Fatal error:  Uncaught AssertionError: assert($result['handler'] !== null) in /home/wouter/projects/github.com/L3tum/php-router-benchmark/benchmark/FastRouteBench.php:41
    Stack trace:
    #0 /home/wouter/projects/github.com/L3tum/php-router-benchmark/benchmark/FastRouteBench.php(41): assert()
    #1 /tmp/PhpBench4a5kcG(57): Benchmark\FastRouteBench->benchDynamicRoutes()
    #2 {main}
      thrown in /home/wouter/projects/github.com/L3tum/php-router-benchmark/benchmark/FastRouteBench.php on line 41
   ```

**Comment by L3tum** [comment]
Thanks for the logs!

I missed that all files in the `src` folder are ignored. The latest commit should fix this.

**Comment by wouterj** [comment]
Hi @L3tum thanks for the quick response :)

(1) is now indeed fixed. However, the errors of (2) still pop-up when running `make`.

**Comment by L3tum** [comment]
Ah, PHPStorm seems to have moved one of the commands in the Makefile when I created the sample Router^^
Should be fixed now. Case 3 should also be fixed, seems to have been a faulty copy when I moved to this repo.

**Comment by wouterj** [comment]
Yay, it works. Thank you @L3tum!

Also thanks for sharing your findings/ideas publicly, allowing the whole PHP community to progress forward. Let's see if I can find why Symfony Routing is this much slower (I do expect it to be as fast as or faster than FastRoute, given the FastRoute inspired development done in the past 3 years).
